[versions]
kotlin = "2.3.0"
kotlinter = "5.3.0"
kermit = "2.0.8"
dokka = "2.1.0"
compose = "1.8.0"
kobweb = "0.23.3"
serialization = "1.8.0"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core", version.ref = "kobweb" }
kobweb-silk = { module = "com.varabyte.kobweb:kobweb-silk", version.ref = "kobweb" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
kobweb = ['kobweb-silk', 'kobweb-core']
